sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/


before_script:
  - sudo apt-get install libav-tools
  - sudo apt-get install youtube-dl
  - sudo ln -s `which youtube-dl` /usr/local/bin/youtube-dl
  - sudo ln -s `which avconv` /usr/local/bin/ffmpeg
  - sudo ln -s `which avprobe` /usr/local/bin/ffprobe
  - ./gradlew npmInstall

script:
  - ./gradlew docker -x integrationTest


after_success:
  - docker login  -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker tag  lumue/woelkchen_download:master-SNAPSHOT lumue/woelkchen_download:latest
  - docker push lumue/woelkchen_download:master-SNAPSHOT
  - docker push lumue/woelkchen_download:latest
  - docker tag  lumue/kodi-api-service:master-SNAPSHOT lumue/kodi-api-service:latest
  - docker push lumue/kodi-api-service:master-SNAPSHOT
  - docker push lumue/kodi-api-service:latest

